version: "3"

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123mudar"
    ports:
      - "15432:5432"
    volumes:
      - volume:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rogerio@indemetal.com.br"
      PGADMIN_DEFAULT_PASSWORD: "123mudar"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
